### ISSUE TITLE
Has anyone tried this syn bn on segmentation task? 

### ISSUE THREAD

**Issue by wy3406** [duducheng/deeplabv3p_gluon#1]
Use the syn bn can improve the segmentation task performance?

**Comment by duducheng** [comment]
I have not compared them yet, you can also try your own.

If I have the results later, I'll put them here.

**Comment by wy3406** [comment]
Hi,
Have you tried to configure the {WEIGHTS=None} parameter in the {train_multi_gpu.py} file?When I set it to  {WEIGHTS=None}, the program can only run one thread (the {parallel_apply} function in the {parallel.py} file knows that only {thread. join} has been completed once), and the program runs normally when there is an initialization model.but I don't know why?
