### ISSUE TITLE
Deadlock in multi-gpu training

### ISSUE THREAD

**Issue by zhijiew** [duducheng/deeplabv3p_gluon#5]
Hi, thank you for your nice codes!

When I train the multi-gpu version, my code is stuck in [this line](https://github.com/duducheng/deeplabv3p_gluon/blob/master/train_multi_gpu.py#L85), I can not get the outputs, no errors or other infos, just stuck. and I can train the single gpu version painless.

Do you have any idea about this problem?

Conda environment:
Python 3.6.6
mxnet-cu90      1.3.0b20180801
gluoncv         0.3.0b20180818

GPU:
Tesla M40 * 2

Training settings:
FLAG = 'train_aug_multi_gpu_1e-3'
EPOCHS = 50
BATCH = 8
TEST_BATCH = 64
TRAIN_SPLIT = 'train_aug'
TRAIN_OS = 16
USE_GLOBAL_STATS = False
DATA_ROOT = os.path.expanduser('~/.mxnet/datasets/voc')
WEIGHTS = 'tmp_weights/imagenet_coco_pretrained/imagenet_coco_pretrained.params'
LR = 1.e-3
CHECKPOINT_INTERVAL = 5
N_GPUS = 2

**Comment by duducheng** [comment]
I offer some aspects:

1. Try not to use SyncBatchNorm
2. Try to check the gluoncv DataParallel, or write your own multi gpu version.
3. I observe some performance diff between 1080, Titan Xp, K80 and V100. There may be some problem of mxnet on gpu environment, try other machine for debug.

I’m sorry that I don’t have clear idea about it. Good luck!
